"use server";

import { db } from "@/lib/prisma";
import { auth } from "@clerk/nextjs/server";
import { GoogleGenerativeAI } from "@google/generative-ai";

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

// Generate solution using Gemini AI
export async function generateSolutionWithAI(challengeId, language = "python") {
  try {
    const challenge = await db.codingChallenge.findUnique({
      where: { id: challengeId },
    });

    if (!challenge) {
      throw new Error("Challenge not found");
    }

    const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });

    const prompt = `You are an expert programmer. Generate a CORRECT and WORKING solution for the following coding challenge.

Challenge: ${challenge.title}

Problem Description:
${challenge.description}

Constraints:
${challenge.constraints || "No specific constraints provided"}

Examples:
${challenge.examples?.map(ex => `Input: ${ex.input}\nOutput: ${ex.output}\nExplanation: ${ex.explanation}`).join('\n\n') || "No examples provided"}

Please provide a complete, working solution in ${language} that solves this problem correctly. 
The solution should pass all test cases and handle edge cases properly.
Return ONLY the code, no explanations or markdown formatting. Start directly with the code.

Important: Make sure the solution:
1. Defines a function called "solution" that takes the appropriate parameters
2. Works with the test harness that will call it
3. Returns the correct output type expected by the test cases`;

    const result = await model.generateContent(prompt);
    const response = result.response;
    const solution = response.text();

    console.log("[AI Solution Generation] Generated solution for:", challenge.title);

    return {
      success: true,
      solution: solution,
      message: "Solution generated by AI. Click 'Run Test Cases' to verify it passes all tests!",
    };
  } catch (error) {
    console.error("[AI Solution Generation] Error:", error);
    throw new Error(`Failed to generate solution: ${error.message}`);
  }
}

// Check student's code solution with AI
export async function checkSolutionWithAI(challengeId, studentCode, language = "python") {
  try {
    const challenge = await db.codingChallenge.findUnique({
      where: { id: challengeId },
    });

    if (!challenge) {
      throw new Error("Challenge not found");
    }

    const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });

    const evaluationPrompt = `You are an expert code reviewer. Evaluate the student's solution for this coding challenge.

Challenge: ${challenge.title}

Problem Description:
${challenge.description}

Constraints:
${challenge.constraints || "No specific constraints provided"}

Examples:
${challenge.examples?.map(ex => `Input: ${ex.input}\nOutput: ${ex.output}\nExplanation: ${ex.explanation}`).join('\n\n') || "No examples provided"}

Student's Code (${language}):
\`\`\`${language}
${studentCode}
\`\`\`

Please evaluate this code and respond with:
1. CORRECT or INCORRECT (start with one of these words)
2. If CORRECT: Briefly explain why the solution is correct
3. If INCORRECT: Explain what's wrong and provide the correct solution in ${language}

Format your response clearly with sections.`;

    const result = await model.generateContent(evaluationPrompt);
    const response = result.response;
    const evaluation = response.text();

    console.log("[AI Code Check] Evaluated solution for:", challenge.title);

    const isCorrect = evaluation.toUpperCase().startsWith("CORRECT");

    return {
      success: true,
      isCorrect,
      evaluation,
      message: isCorrect 
        ? "✅ Great! Your solution is correct!"
        : "❌ Your solution needs improvement. See feedback below.",
    };
  } catch (error) {
    console.error("[AI Code Check] Error:", error);
    throw new Error(`Failed to check solution: ${error.message}`);
  }
}

// Get all coding challenges
export async function getCodingChallenges(filters = {}) {
  try {
    const challenges = await db.codingChallenge.findMany({
      where: {
        ...(filters.difficulty && { difficulty: filters.difficulty }),
        ...(filters.category && { category: filters.category }),
      },
      orderBy: {
        createdAt: "desc",
      },
    });

    return challenges || [];
  } catch (error) {
    console.error("Error fetching challenges:", {
      message: error.message,
      code: error.code,
      clientVersion: error.clientVersion,
      stack: error.stack,
    });
    // Return empty array instead of throwing to prevent route crashes
    return [];
  }
}

// Get single coding challenge
export async function getCodingChallenge(challengeId) {
  try {
    const challenge = await db.codingChallenge.findUnique({
      where: { id: challengeId },
    });

    if (!challenge) {
      throw new Error("Challenge not found");
    }

    // Get user's previous submissions for this challenge
    const { userId } = auth();
    if (!userId) {
      return { challenge, userSubmissions: [], stats: null };
    }

    const user = await db.user.findUnique({
      where: { clerkUserId: userId },
    });

    if (!user) {
      return { challenge, userSubmissions: [], stats: null };
    }

    const submissions = await db.codeSubmission.findMany({
      where: {
        userId: user.id,
        challengeId,
      },
      orderBy: {
        submissionTime: "desc",
      },
      take: 10, // Last 10 submissions
    });

    // Calculate stats
    const allSubmissions = await db.codeSubmission.findMany({
      where: {
        userId: user.id,
        challengeId,
      },
    });

    const stats = {
      totalSubmissions: allSubmissions.length,
      accepted: allSubmissions.filter((s) => s.verdict === "accepted").length,
      tried: new Date(submissions[0]?.createdAt || new Date()),
    };

    return { challenge, userSubmissions: submissions, stats };
  } catch (error) {
    console.error("Error fetching challenge:", error);
    throw new Error("Failed to fetch challenge");
  }
}

// Run test cases for code submission
export async function runTestCases(challengeId, code, language) {
  try {
    const challenge = await db.codingChallenge.findUnique({
      where: { id: challengeId },
    });

    if (!challenge) {
      throw new Error("Challenge not found");
    }

    // Parse test cases
    const testCases = challenge.testCases || [];
    const results = [];

    for (const testCase of testCases) {
      try {
        // Transform test case to Django-compatible format
        // Django expects: { input: [...], expected: "output" }
        // Our test case has: { input: "...", expectedOutput: "..." }
        
        let transformedInput = testCase.input;
        try {
          // Try to parse input as JSON array or list notation
          if (testCase.input.includes("[") && testCase.input.includes("]")) {
            // Try parsing as JSON array
            transformedInput = JSON.parse(testCase.input.split("\n")[0]);
          } else if (!isNaN(testCase.input)) {
            // Single number
            transformedInput = parseInt(testCase.input);
          }
        } catch (e) {
          // If parsing fails, keep input as string
          transformedInput = testCase.input;
        }

        console.log(`[Test ${idx + 1}] Input: ${JSON.stringify(transformedInput)}, Expected: ${testCase.expectedOutput}`);

        const response = await fetch(
          `${process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000"}/api/code-execution`,
          {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
            },
            body: JSON.stringify({
              code,
              language,
              stdin: "",
              testCases: [
                {
                  input: transformedInput,
                  expected: testCase.expectedOutput,
                  funcName: "solution",
                }
              ],
            }),
          }
        );

        const result = await response.json();
        
        console.log(`[Test ${idx + 1}] Response:`, {
          success: result.success,
          output: result.output?.substring(0, 50),
          hasTestResults: (result.testResults && result.testResults.length > 0),
          testResultCount: result.testResults?.length || 0,
          error: result.error,
        });

        if (!result.success && result.isDemoMode) {
          // In demo mode, don't fail the test - just mark it as pending
          results.push({
            testCaseId: testCase.id,
            passed: true, // Assume passed in demo mode
            expectedOutput: testCase.expectedOutput,
            actualOutput: "Demo mode - Code execution not available",
            error: null,
            isDemoMode: true,
          });
        } else if (!result.testResults || result.testResults.length === 0) {
          // No test results - execution might have failed
          console.error(`[Test ${idx + 1}] No test results returned`);
          results.push({
            testCaseId: testCase.id,
            passed: false,
            expectedOutput: testCase.expectedOutput || "",
            actualOutput: result.output || "",
            error: result.error || "Test execution failed - no result returned",
          });
        } else {
          // Get the first (and only) test result
          const testResult = result.testResults[0];
          
          console.log(`[Test ${idx + 1}] Full test result object:`, testResult);

          if (!testResult) {
            results.push({
              testCaseId: testCase.id,
              passed: false,
              expectedOutput: testCase.expectedOutput || "",
              actualOutput: "",
              error: "No test result returned",
            });
            continue;
          }

          // Extract output from test result - handle various possible field names
          const actualOutput = String(testResult.output ?? testResult.got ?? testResult.actualOutput ?? "");
          const expectedOutput = String(testCase.expectedOutput ?? "");
          const passed = testResult.passed === true;

          // Sanity check on the outputs
          if (!actualOutput && !expectedOutput && testResult.error) {
            console.error(`[Test ${idx + 1}] No output captured, but error exists:`, testResult.error);
          }

          results.push({
            testCaseId: testCase.id,
            passed,
            expectedOutput: expectedOutput,
            actualOutput: actualOutput,
            error: testResult.error || null,
          });
        }
      } catch (error) {
        console.error(`[Test ${idx + 1}] Exception:`, error);
        results.push({
          testCaseId: testCase.id,
          passed: false,
          expectedOutput: testCase.expectedOutput || "",
          actualOutput: "",
          error: error.message,
        });
      }
    }

    const passedCount = results.filter((r) => r.passed).length;
    const isDemoMode = results.some((r) => r.isDemoMode);
    const verdict =
      passedCount === testCases.length
        ? "accepted"
        : passedCount > 0
        ? "partially_correct"
        : "wrong_answer";

    return {
      success: true,
      tests: results,
      passedTests: passedCount,
      totalTests: testCases.length,
      verdict,
      isDemoMode,
    };
  } catch (error) {
    console.error("Error running test cases:", error);
    return {
      success: false,
      error: error.message,
      tests: [],
      passedTests: 0,
      totalTests: 0,
      verdict: "error",
    };
  }
}

// Submit code solution
export async function submitCodeSolution(
  challengeId,
  code,
  language,
  testResults
) {
  try {
    const { userId } = auth();
    if (!userId) {
      throw new Error("User not authenticated");
    }

    const user = await db.user.findUnique({
      where: { clerkUserId: userId },
    });

    if (!user) {
      throw new Error("User not found");
    }

    // Determine verdict
    const totalTests = testResults?.totalTests || 0;
    const passedTests = testResults?.passedTests || 0;
    const verdict =
      passedTests === totalTests && totalTests > 0
        ? "accepted"
        : passedTests > 0
        ? "partially_correct"
        : testResults?.verdict || "wrong_answer";

    // Create submission record
    const submission = await db.codeSubmission.create({
      data: {
        userId: user.id,
        challengeId,
        language,
        code,
        verdict,
        status: "completed",
        passedTests: passedTests || 0,
        totalTests: totalTests || 0,
        testResults: testResults?.tests || [],
      },
    });

    // Update challenge stats if accepted
    if (verdict === "accepted") {
      await db.codingChallenge.update({
        where: { id: challengeId },
        data: {
          submissionCount: { increment: 1 },
          acceptance: {
            // This is a simplified calculation
            set: Math.random() * 100, // In real app, calculate based on actual data
          },
        },
      });
    }

    return {
      success: true,
      submission,
      message:
        verdict === "accepted"
          ? "🎉 Congratulations! All tests passed!"
          : `${passedTests}/${totalTests} tests passed`,
    };
  } catch (error) {
    console.error("Error submitting solution:", error);
    throw new Error("Failed to submit solution");
  }
}

// Get user's submission history
export async function getSubmissionHistory(challengeId = null) {
  try {
    const { userId } = auth();
    if (!userId) {
      throw new Error("User not authenticated");
    }

    const user = await db.user.findUnique({
      where: { clerkUserId: userId },
    });

    if (!user) {
      throw new Error("User not found");
    }

    const submissions = await db.codeSubmission.findMany({
      where: {
        userId: user.id,
        ...(challengeId && { challengeId }),
      },
      orderBy: {
        submissionTime: "desc",
      },
      take: 50,
    });

    return submissions;
  } catch (error) {
    console.error("Error fetching submission history:", error);
    throw new Error("Failed to fetch submission history");
  }
}

// Get user's coding statistics
export async function getUserCodingStats() {
  try {
    const { userId } = auth();
    if (!userId) {
      // Return default stats if user not authenticated
      return {
        totalSubmissions: 0,
        totalAccepted: 0,
        totalAttempted: 0,
        acceptanceRate: 0,
        languageDistribution: {},
        recentSubmissions: [],
      };
    }

    const user = await db.user.findUnique({
      where: { clerkUserId: userId },
    });

    if (!user) {
      // Return default stats if user not found
      return {
        totalSubmissions: 0,
        totalAccepted: 0,
        totalAttempted: 0,
        acceptanceRate: 0,
        languageDistribution: {},
        recentSubmissions: [],
      };
    }

    const submissions = await db.codeSubmission.findMany({
      where: { userId: user.id },
    });

    const accepted = submissions.filter(
      (s) => s.verdict === "accepted"
    ).length;
    const attempted = new Set(submissions.map((s) => s.challengeId)).size;
    const totalSubmissions = submissions.length;

    // Language distribution
    const languageDistribution = {};
    submissions.forEach((s) => {
      languageDistribution[s.language] =
        (languageDistribution[s.language] || 0) + 1;
    });

    return {
      totalSubmissions,
      totalAccepted: accepted,
      totalAttempted: attempted,
      acceptanceRate:
        totalSubmissions > 0 ? ((accepted / totalSubmissions) * 100).toFixed(1) : 0,
      languageDistribution,
      recentSubmissions: submissions.slice(0, 5),
    };
  } catch (error) {
    console.error("Error fetching user stats:", error);
    // Return default stats on error instead of throwing
    return {
      totalSubmissions: 0,
      totalAccepted: 0,
      totalAttempted: 0,
      acceptanceRate: 0,
      languageDistribution: {},
      recentSubmissions: [],
    };
  }
}
